# -*- coding: utf-8 -*-
"""convertToEla.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tEx-yI3mv1ZV0Swco1wcbT-Wc2JmwwwS
"""


import os
#from pylab import *
from PIL import Image, ImageChops, ImageEnhance

def convert_to_ela_image(path, quality):
    filename = path
    resaved_filename = filename.split('.')[0] + '.resaved.jpg'
    ELA_filename = filename.split('.')[0] + '.ela.png'
    
    im = Image.open(filename).convert('RGB')
    im.save(resaved_filename, 'JPEG', quality=quality)
    resaved_im = Image.open(resaved_filename)
    
    ela_im = ImageChops.difference(im, resaved_im)
    
    extrema = ela_im.getextrema()
    max_diff = max([ex[1] for ex in extrema])
    if max_diff == 0:
        max_diff = 1
    scale = 255.0 / max_diff
    
    ela_im = ImageEnhance.Brightness(ela_im).enhance(scale)
    
    return ela_im

def get(path):
  X = []
  X.append(array(convert_to_ela_image(path, 90).resize((128, 128))).flatten() / 255.0)
  X = X.reshape(-1, 128, 128, 3)
  return X;